feat(dashmate): report pulled images during update
dashpay/platform pull request #1186
Opened 2023-06-21 21:31 UTC by pshenmic

## Issue being fixed or feature implemented

Dashmate should show info about the images of the service that has been pull during update https://github.com/dashpay/platform/issues/105

## What was done?

TBD

## How Has This Been Tested?

TBD

## Breaking Changes

TBD

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-06-29 11:41 UTC, pshenmic commented
Test results:

Default output:

<img width="555" alt="image" src="https://github.com/dashpay/platform/assets/17009187/280f6aed-fc6b-40b3-a26c-6b671ba18291">

Format json:

```
$ dashmate update --format=json
[{"serviceName":"core","title":"Core","pulled":false,"image":"dashpay/dashd:19.2.0"},{"serviceName":"drive_abci","title":"Drive ABCI","pulled":false,"image":"dashpay/drive:0.24"},{"serviceName":"drive_tenderdash","title":"Drive Tenderdash","pulled":true,"image":"dashpay/tenderdash:0.11.2"},{"serviceName":"dapi_api","title":"DAPI API","pulled":false,"image":"dashpay/dapi:0.24"},{"serviceName":"dapi_envoy","title":"DAPI Envoy","pulled":false,"image":"dashpay/envoy:0.24"},{"serviceName":"dashmate_helper","title":"Dashmate Helper","pulled":false,"image":"dashpay/dashmate-helper:0.24"}]
```

2023-06-29 12:50 UTC, shumkov commented on packages/dashmate/src/commands/update.js
> +                serviceName, humanName, image, pulled,
let's call it `updated`?

2023-06-29 13:09 UTC, shumkov requested changes

2023-06-29 13:09 UTC, shumkov commented on packages/dashmate/src/docker/DockerCompose.js
> +    if (await this.isNodeRunning(envs, serviceName)) {
It's little bit wired to pass service name to `isNodeRunning` function. I would recommend to have two methods:
- `isNodeRunning` which will rely on compose files
- `isServiceRunning` which will accept service name (not optional)

2023-07-03 03:53 UTC, shumkov requested changes

2023-07-03 03:53 UTC, shumkov commented on packages/dashmate/src/listr/tasks/updateNodeTaskFactory.js
> +const _ = require('lodash');
It's not using Listr so it must be outside of `listr/task`. Let's create `src/update` and name it `updateServiceImagesFactory`

2023-07-03 03:53 UTC, shumkov commented on packages/dashmate/src/listr/tasks/updateNodeTaskFactory.js
> +                serviceName, title, image, pulled,
pulled -> updated

2023-07-03 03:53 UTC, shumkov commented on packages/dashmate/src/docker/getServiceListFactory.js
> +        serviceName: 'core',
rename to `name`

2023-07-03 03:53 UTC, shumkov commented on packages/dashmate/src/commands/update.js
> +    printObject(updated
You should use printArrayOfObjects

2023-07-03 03:53 UTC, shumkov commented on packages/dashmate/src/printers/printObject.js
> +function printObject(object, format, flatten = true) {
`printArrayOfObjects` already does it

2023-07-03 09:59 UTC, shumkov requested changes

2023-07-03 09:59 UTC, shumkov commented on packages/dashmate/src/docker/DockerCompose.js
> +   * @param {Object} options optional
Optional params must be in square brackets, also you can specify default values

2023-07-03 11:36 UTC, shumkov approved these changes
👍

2023-07-03 17:23 UTC, merged