feat(dashmate): setup masternode with DMT
dashpay/platform pull request #1203
Opened 2023-06-27 12:01 UTC by shumkov

## Issue being fixed or feature implemented

Dash Masternode Tool is recommended way to register masternode for mainnet but it was missed in dashmate setup

## What was done?

- Add DMT as a choice to register a masternode
- Disabled mobile wallets since they do not provide all required functionality
- Fixed initial values for IP and ports form
- Disable e2e tests (not stable)

## How Has This Been Tested?

Manually

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2023-06-27 13:06 UTC, jawid-h submitted a review, later dismissed

2023-06-27 15:24 UTC, thephez reviewed
I tested this a bit and left a few suggestions.

Also I noticed a couple small unexpected things:

- If you've already registered your MN, it will require you to enter the BLS key as expected with no pre-generated key in the field. In the next step, it then asks for the platform key, but actually shows a generated key. This should be unnecessary for already registered nodes (because they've already defined a key when registering).
- When I ran through the DMT (testnet) setup, it didn't pre-fill the ports with default values like it used to. I'm not sure if that was intentional or not, but I liked having some defaults there.

2023-06-27 15:24 UTC, thephez commented on packages/dashmate/src/listr/prompts/createIpAndPortsForm.js
When I ran through the DMT (testnet) setup, it didn't pre-fill the ports with default values like it used to. I'm not sure if that was intentional or not, but I liked having some defaults there.

2023-06-27 15:24 UTC, thephez commented on packages/dashmate/src/listr/prompts/registerMasternode/registerMasternodeWithDMT.js
> +  key is a BLS private key, encoded in HEX format. Dashmate will record the
```suggestion
  key is a BLS private key, encoded in hexadecimal format. Dashmate will record the
```

2023-06-27 15:24 UTC, thephez commented on packages/dashmate/src/listr/tasks/setup/regular/registerMasternodeGuideTaskFactory.js
> +      // TODO: Disabled until additional functionality like signing protx and so on is not
```suggestion
      // TODO: Disabled until additional functionality like signing protx and so on is
```

2023-06-27 16:07 UTC, shumkov commented
@thephez Thank you for your comments and suggestions. I will make fixes tomorrow.

2023-06-28 02:34 UTC, shumkov commented
> When I ran through the DMT (testnet) setup, it didn't pre-fill the ports with default values like it used to. I'm not sure if that was intentional or not, but I liked having some defaults there.

You are supposed to use once what you set in DMT, so that's why they are empty.

2023-06-28 02:58 UTC, strophy requested changes

2023-06-28 02:58 UTC, strophy commented on packages/dashmate/src/listr/prompts/registerMasternode/registerMasternodeWithCoreWallet.js
> +  Please follow instructions on how to send a collateral in Dash Core Wallet:
```suggestion
  Please follow the instructions on how to create a collateral funding transaction in Dash Core Wallet:
```

2023-06-28 02:58 UTC, strophy commented on packages/dashmate/src/listr/prompts/registerMasternode/registerMasternodeWithDMT.js
> +      header: `  Complete the initial DMT setup then return here to continue:
```suggestion
      header: `  Complete initial DMT setup and return here to continue:
```

2023-06-28 03:04 UTC, strophy approved these changes

2023-06-28 03:05 UTC, strophy submitted a review, later dismissed

2023-06-28 03:56 UTC, strophy approved these changes

2023-06-28 06:42 UTC, strophy approved these changes

2023-06-28 07:12 UTC, merged