feat(dashmate): successful migration test
dashpay/platform pull request #1500
Opened 2023-10-18 08:22 UTC by pshenmic

## Issue being fixed or feature implemented

Add a test that will run the migration config code and check if it is valid, executable and contains right image versions

## What was done?

* Added a unit test for successful migration
* Added a e2e test for --platform flag on start / stop regular nodes

## How Has This Been Tested?

Locally

## Breaking Changes

No

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-10-19 03:51 UTC, pshenmic commented
https://github.com/dashpay/platform/issues/1275

2023-10-23 07:13 UTC, shumkov requested changes

2023-10-23 07:13 UTC, shumkov commented on packages/dashmate/test/unit/commands/config/configFile/migrateConfigFileFactory.js
> +const _ = require('lodash');
.spec.js

2023-10-23 07:13 UTC, shumkov commented on packages/dashmate/configs/defaults/getTestnetConfigFactory.js
> +          image: 'dashpay/dashd:20.0.0-beta.4',
Please update version a separate PR

2023-10-23 17:08 UTC, shumkov approved these changes
👍

2023-10-24 05:41 UTC, merged