feat(dashmate): add cli command for core service
dashpay/platform pull request #1501
Opened 2023-10-18 08:24 UTC by pshenmic

## Issue being fixed or feature implemented

Add a dashmate command to execute dash-cli commands in the core container. This is very useful, when you need to do something or check something with the dash-cli of the current node, but you have to use `docker exec -it..` instead.

## What was done?

* Added a cli command in the core folder

## How Has This Been Tested?

Locally

## Breaking Changes

No

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-10-19 04:13 UTC, shumkov requested changes

2023-10-19 04:13 UTC, shumkov commented on packages/dashmate/src/commands/core/cli.js
> +
Let's add a check is service running?

2023-10-19 04:13 UTC, shumkov commented on packages/dashmate/src/commands/core/cli.js
> +class DashCliCommand extends ConfigBaseCommand {
CliCommand

2023-10-19 04:23 UTC, pshenmic commented
Tested locally

With started testnet fullnode:
```
pshenmic@Mikhails-MacBook-Pro dashmate % yarn dashmate core cli "getblockhash 1"
0000047d24635e347be3aaaeb66c26be94901a2f962feccd4f95090191f208c1
```

With stopped testnet fullnode

```
pshenmic@Mikhails-MacBook-Pro dashmate % yarn dashmate core cli "getblockhash 1"
    ServiceIsNotRunningError: Service core for testnet is not running. Please run the service first.
```

2023-10-23 07:06 UTC, shumkov approved these changes
Nice 👍

2023-10-23 09:40 UTC, merged