Feat/register
dashpay/platform pull request #1596
Opened 2023-11-23 11:37 UTC by lklimek

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2024-02-08 11:55 UTC, QuantumExplorer requested changes

2024-02-08 11:58 UTC, QuantumExplorer commented on packages/rs-sdk/src/core_client.rs
> +        _core_chain_locked_height: u32,
I mean _core_chain_locked_height: u32, if it isn't being used.

2024-02-08 12:52 UTC, lklimek reviewed
LGTM, some comments added that can be handled in separate PR

2024-02-08 12:52 UTC, lklimek commented on packages/rs-drive-proof-verifier/src/provider.rs
> +    /// Use `dash_platform_sdk::SdkBuilder::with_dump_dir()` to generate quorum keys files.
is is rs-sdk or dash_platform_sdk? please check all renames

2024-02-08 12:52 UTC, lklimek commented on packages/rs-sdk/src/core_client.rs
> +        _core_chain_locked_height: u32,
agree

2024-02-08 12:52 UTC, lklimek commented on packages/rs-sdk/src/platform/put.rs
> +//! Module containing the Put trait, allowing modification of objects (state transitions) on the Dash Platform.
this file is unused as state transitions turned out to be much more complex than I expected. To be removed.

2024-02-08 12:54 UTC, lklimek commented on packages/rs-drive-abci/src/execution/platform_events/identity_credit_withdrawal/fetch_and_prepare_unsigned_withdrawal_transactions/v0/mod.rs
> +use dashcore_rpc::dashcore::{
delete this file, looks like leftover

2024-02-08 13:03 UTC, lklimek commented on packages/rs-sdk/Cargo.toml
>  drive-abci = { path = "../rs-drive-abci", default-features = false }
please address `cargo machete` output, https://github.com/dashpay/platform/actions/runs/7828491935/job/21358511981?pr=1596 (needs to be double-checked as machete is not perfect, for example when sth is hidden behind feature)

2024-02-08 15:13 UTC, fominok commented on packages/rs-drive-abci/Cargo.toml
> +dashcore-rpc = { git = "https://github.com/dashpay/rust-dashcore-rpc", branch = "master" }
good catch, no idea how it comes back every time like that

2024-02-12 16:43 UTC, QuantumExplorer commented
Awesome work from all involved, very happy to see this one merged in.

2024-02-12 16:44 UTC, merged