feat: rs-sdk is thread safe and doesn't require &mut
dashpay/platform pull request #1620
Opened 2023-12-06 13:21 UTC by lklimek

## Issue being fixed or feature implemented

`rs-sdk` should not require mutable references, as it complicates usage of the Sdk.
For example,it might require locking.

## What was done?

We use Arc<Sdk> and lock inside Sdk whenever required.

Also some smaller refactorings implemented, for example:

* added CancellationToken to allow cancelling of execution
* refactored ContextProvider mock as GrpcContextProvider

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-12-07 07:55 UTC, shumkov requested changes

2023-12-07 07:55 UTC, shumkov commented on .github/workflows/tests.yml
>      branches:
Let's just run on any branch. I'm always with this

2023-12-07 07:55 UTC, shumkov commented on packages/rs-sdk/src/sdk.rs
> +    pub fn set_context_provider<C: ContextProvider + 'static>(&self, context_provider: C) {
Not sure I like this naming. For me context is kinda an application context, so it should be contracts for app, current user identity. Shall we call it state adapter or state repository or something like that?

2023-12-07 07:56 UTC, shumkov commented
I think we should extract context logic from this PR and keep only thread safe stuff

2023-12-07 10:32 UTC, lklimek commented on packages/rs-sdk/src/core_client.rs
> +    pub fn _sign_raw_transaction_with_wallet<R: RawTx>(
removed

2023-12-08 11:50 UTC, shumkov approved these changes
Nice improvement 👍

2023-12-12 12:22 UTC, merged