feat(dashmate): check for DKG before stopping node
dashpay/platform pull request #1683
Opened 2024-01-30 19:43 UTC by pshenmic

## Issue being fixed or feature implemented

https://github.com/dashpay/platform/issues/1648

When node is participating in DKG exchange process, it is dangerous to restart the node, because it can result to the POSE ban. This PR adds a check for that before stopping node

## What was done?

* Added a check in `stopNodeTaskFactory`

## How Has This Been Tested?

Locally

## Breaking Changes

No

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2024-01-31 06:37 UTC, shumkov requested changes

2024-01-31 06:37 UTC, shumkov commented on packages/dashmate/src/listr/tasks/stopNodeTaskFactory.js
> +        skip: (ctx) => ctx.isForce || config.get('network') === NETWORK_LOCAL,
I would do enable instead of skip

2024-01-31 06:40 UTC, shumkov requested changes

2024-01-31 06:40 UTC, shumkov commented on packages/dashmate/src/listr/tasks/stopNodeTaskFactory.js
> +            const agreement = await task.prompt({
What if we call it in non interactive mode?

2024-03-18 15:08 UTC, shumkov commented on packages/dashmate/src/listr/tasks/stopNodeTaskFactory.js
> +            const agreement = await task.prompt({
Probably the combination would be the best. If we pass safe, then during DKG it should throw an error.

2024-04-22 09:34 UTC, shumkov commented on packages/dashmate/src/listr/tasks/stopNodeTaskFactory.js
> +            const agreement = await task.prompt({
We had a call with @pshenmic and decided when a user does restart or stop, we throw en error if the node is in the middle of DKG. He can pass `--force` to do the command anyway. We also provide a flag `--safe` that make command wait until DKG passed.

2024-05-06 03:34 UTC, shumkov requested changes

2024-05-06 03:34 UTC, shumkov commented on packages/dashmate/src/core/quorum/waitForDKGWindowPass.js
> +  const { result: startBlockchainInfo } = await rpcClient.getBlockchainInfo();
Blockchain info is very slow. Why not use get block count?

2024-05-06 03:34 UTC, shumkov commented on packages/dashmate/src/constants.js
> +export const MIN_BLOCKS_BEFORE_DKG = 6;
What this interval means? Please add a comment to explain

2024-05-06 03:34 UTC, shumkov commented on packages/dashmate/src/core/quorum/waitForDKGWindowPass.js
> +    await wait(1000);
Let's do 10 seconds? Another option is to subscribe to ZMQ to receive notifications about new blocks

2024-05-08 03:27 UTC, shumkov requested changes

2024-05-08 03:27 UTC, shumkov commented on packages/dashmate/src/core/quorum/waitForDKGWindowPass.js
> +    const { result: blockchainInfo } = await rpcClient.getBlockchainInfo();
getBlockCount? I think you should use do while loop to reduce this duplication

2024-05-08 05:28 UTC, shumkov approved these changes
👍

2024-05-14 22:22 UTC, merged

2024-05-15 04:07 UTC, qwizzie commented
Nice job.