feat!: getIdentitiesContractKeys endpoint
dashpay/platform pull request #1766
Opened 2024-03-12 17:53 UTC by markin-io

## Issue being fixed or feature implemented

Remove `getIdentities` and `getIdentitiesByPublicKeyHashes` queries, and add `getIdentitiesContractKeys` as a replacement

## What was done?

- Remove queries from proto messages
- Remove queries from drive
- Update JS and Rust clients 
- Added `getIdentitiesContractKeys` and e2e test

## How Has This Been Tested?

- CI

## Breaking Changes

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2024-03-18 15:02 UTC, shumkov requested changes

2024-03-18 15:02 UTC, shumkov commented on packages/platform-test-suite/test/functional/platform/proofs.spec.js
> +          it.skip('should be able to verify that multiple identities exist with getIdentitiesByPublicKeyHashes', async () => {
Just remove?

2024-03-18 15:04 UTC, shumkov submitted a review, later dismissed
👍

2024-03-18 15:18 UTC, QuantumExplorer requested changes

2024-03-18 15:18 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/query/identity_based_queries/identities/mod.rs
> -            .identities;
You forgot to remove the query version.

2024-03-19 12:29 UTC, shumkov approved these changes
👍

2024-03-19 13:33 UTC, QuantumExplorer commented
Let's wait on the new methods needed before this one is merged in.

2024-03-29 07:28 UTC, QuantumExplorer commented on packages/dapi-grpc/protos/platform/v0/platform.proto
> +    repeated bytes ids = 1;
How is this going to work if you don't have the SearchKey?

2024-03-29 07:30 UTC, QuantumExplorer commented on packages/dapi-grpc/protos/platform/v0/platform.proto
> +    message IdentitiesKeys { map<string, Keys> entries = 1; };
We don't use a map anywhere else and instead give back the values as a vec in the same order it was requested. I'm not super against using a map, I just think that it breaks consistency.

2024-03-29 07:32 UTC, QuantumExplorer commented on packages/dapi-grpc/build.rs
> -        "GetIdentitiesResponse",
Same

2024-03-29 07:33 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/query/identity_based_queries/identities_keys/v0/mod.rs
> +            // }
todo...

2024-03-29 07:42 UTC, QuantumExplorer requested changes
The reason why we are not querying all identity information is because we could have 100s of keys on each identity. There is no benefit in getting back all keys for many identities. The goal here is to get specific keys for many identities. For example in Dashpay Dapp if I had 25 contacts, I would want to query the Dashpay contract bound encryption and decryption keys for the 25 contacts I have.

2024-03-29 07:42 UTC, QuantumExplorer requested changes
The reason why we are not querying all identity information is because we could have 100s of keys on each identity. There is no benefit in getting back all keys for many identities. The goal here is to get specific keys for many identities. For example in Dashpay Dapp if I had 25 contacts, I would want to query the Dashpay contract bound encryption and decryption keys for the 25 contacts I have.

2024-04-27 19:35 UTC, QuantumExplorer submitted a review, later dismissed

2024-04-27 19:36 UTC, QuantumExplorer approved these changes

2024-04-27 20:24 UTC, merged