feat: provide protocol version in epoch info query
dashpay/platform pull request #1778
Opened 2024-03-15 07:11 UTC by shumkov

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2024-03-19 03:56 UTC, QuantumExplorer requested changes
We should add a test to make sure it works. Maybe in sdk.

2024-03-19 03:56 UTC, QuantumExplorer commented on packages/dapi-grpc/protos/platform/v0/platform.proto
> +    returns (WaitForStateTransitionResultResponse);
Why is the formatting changing?

2024-03-19 03:56 UTC, QuantumExplorer commented on packages/rs-drive/src/drive/verify/system/verify_epoch_infos/v0/mod.rs
> +            // The multipler must be equal to requested keys count
multiplier

2024-03-19 03:56 UTC, QuantumExplorer commented on packages/rs-drive/src/drive/verify/system/verify_epoch_infos/v0/mod.rs
> +                            "core block height must be 4 bytes for a u32".to_string(),
Wrong error message

2024-03-19 03:56 UTC, QuantumExplorer commented on packages/rs-drive/src/drive/verify/system/verify_epoch_infos/v0/mod.rs
> +                        "start time must be an item",
Wrong error message.

2024-03-19 04:08 UTC, shumkov commented
I've added query asserts to existing version upgrade tests

2024-04-04 08:23 UTC, QuantumExplorer approved these changes

2024-04-04 08:52 UTC, QuantumExplorer submitted a review, later dismissed

2024-04-04 12:31 UTC, QuantumExplorer approved these changes

2024-04-04 13:59 UTC, QuantumExplorer approved these changes

2024-04-04 14:45 UTC, merged