feat: identity create replay protection
dashpay/platform pull request #1819
Opened 2024-04-15 11:26 UTC by QuantumExplorer

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2024-04-15 11:37 UTC, shumkov commented on packages/wasm-dpp/src/errors/consensus/basic/identity/identity_asset_lock_state_transition_replay_error.rs
> +        let mut tx_id_bytes = tx_id.to_byte_array();
why do you reverse it?

2024-04-15 11:52 UTC, QuantumExplorer commented on packages/wasm-dpp/src/errors/consensus/basic/identity/identity_asset_lock_state_transition_replay_error.rs
> +        let mut tx_id_bytes = tx_id.to_byte_array();
because it is reversed in other errors.

2024-04-16 09:21 UTC, shumkov requested changes

2024-04-16 09:21 UTC, shumkov commented on packages/rs-drive/src/state_transition_action/system/partially_use_asset_lock_action/v0/transformer.rs
> +        let mut used_tags = asset_lock_value_to_be_consumed.used_tags_ref().clone();
Remove clone

2024-04-16 09:25 UTC, shumkov approved these changes

2024-04-16 10:05 UTC, merged