feat: make sdk transition files public
dashpay/platform pull request #1833
Opened 2024-04-29 15:40 UTC by pauldelucia

## Issue being fixed or feature implemented

Some files of the SDK were not public so they couldn't be accessed from the TUI where they are needed.

## What was done?

Just made the files public.

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [x] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2024-05-01 10:13 UTC, qwizzie commented
Does this affect Dash Platform stability testing (iaw your guide), through use of Platform TUI ? Should we wait on the merger of this pull request ?

2024-05-07 11:56 UTC, pauldelucia commented
> Does this affect Dash Platform stability testing (iaw your guide), through use of Platform TUI ? Should we wait on the merger of this pull request ?
> 
> Edit : or is the relevant part possibly affecting Platform stability testing already merged through pull request 1832 ?

@qwizzie this will just allow for the NFT-related state transitions to be used in the TUI, both in the strategy tests once I add them, and also just in the Contracts screen.

2024-05-09 10:02 UTC, QuantumExplorer requested changes

2024-05-09 10:02 UTC, QuantumExplorer commented on packages/rs-dpp/src/data_contract/document_type/index/mod.rs
> +#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
This change should be behind a feature.

2024-05-09 10:57 UTC, QuantumExplorer approved these changes

2024-05-09 10:58 UTC, QuantumExplorer approved these changes

2024-05-09 11:07 UTC, merged