Feat: state sync
dashpay/platform pull request #1862
Opened 2024-05-27 16:15 UTC by ogabrielides

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2024-05-30 15:02 UTC, shumkov requested changes

2024-05-30 15:02 UTC, shumkov commented on packages/rs-drive-abci/src/abci/handler/offer_snapshot.rs
> +    match request.snapshot {
```rust
let snapshot = request.snapshot.ok_or_else(...)?;
```

2024-05-30 20:56 UTC, ogabrielides commented on packages/rs-drive-abci/src/abci/app/state_sync.rs
> +                let checkpoint_exists = |s: &Snapshot| -> bool {
@shumkov Every N blocks, nodes create a checkpoint of groveDB (file copy?) and then append a new entry containing the snapshot details (checkpoint path, app_hash) at key `SNAPSHOT_KEY` in groveDB.

When a new node completes state sync, it contains all entries at key `SNAPSHOT_KEY` but the checkpoint aren't there.. so if another new node will ask a specific snapshot to be fetched, it won't be possible to be offered.

Hence, when asked, nodes need to return in `list_snapshots` snapshots where corresponding checkpoints are actually there.

2024-06-02 10:28 UTC, ogabrielides commented on packages/rs-drive-abci/src/abci/handler/apply_snapshot_chunk.rs
> +                                }
@shumkov No. When applying a chunk and getting an empty `next_chunk_ids`, internally `state_sync_info` can still expect at least one more chunk (already requested to be fetched). So this is not an invalid situation.

2024-06-02 10:29 UTC, ogabrielides commented on packages/rs-drive-abci/src/abci/handler/apply_snapshot_chunk.rs
> +                        (&request.chunk_id, request.chunk),
Yeah, this needs to be changed in groveDB first.

2024-06-02 20:21 UTC, ogabrielides commented on packages/rs-drive-abci/src/abci/app/consensus.rs
> +    fn platform(&self) -> &'p Platform<C> {
@shumkov handler apply_snapshot_chunk requires that app must implement `SnapshotManagerApplication` and `SnapshotFetchingApplication` and not `PlatformApplication`. (@fominok can explain why)

2025-01-08 21:14 UTC, ogabrielides commented
closing at it will be included in #2413

2025-01-08 21:14 UTC, closed without merging