refactor: extract document faker to crate
dashpay/platform pull request #1887
Opened 2024-06-13 11:42 UTC by shumkov

## Issue being fixed or feature implemented

DPP shouldn't have any external dependencies since this is a public library that is supposed to be cross-platform and cross-environment.

## What was done?

- Extract document faker to a separate crate 

## How Has This Been Tested?

With existing tests. Added to CI

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [x] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2024-06-19 05:23 UTC, QuantumExplorer requested changes

2024-06-19 05:23 UTC, QuantumExplorer commented on packages/rs-random-document/Cargo.toml
> +  "Igor Markin <igor.markin@dash.org>",
I think the authors here are wrong, should be evgeny and you.

2024-06-19 06:24 UTC, fominok commented on packages/rs-random-document/Cargo.toml
> +  "Ivan Shumkov <shumkov@dash.ru>",
dash.ru ?

2024-06-19 06:24 UTC, fominok submitted a review, later dismissed

2024-07-01 13:42 UTC, QuantumExplorer approved these changes

2024-07-01 13:42 UTC, merged