chore: update system data contracts [WIP]
dashpay/platform pull request #1889
Opened 2024-06-13 14:00 UTC by shumkov

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2024-06-19 21:28 UTC, HashEngineering reviewed
ACK

2024-06-24 10:53 UTC, QuantumExplorer commented
We should add "$transferredAt" for DPNS domain

2024-06-24 11:09 UTC, shumkov commented on packages/dashpay-contract/schema/v1/dashpay.schema.json
> +      "avatarUrl": ["avatarHash", "avatarFingerprint"],
We need `minLength`

2024-06-24 11:11 UTC, shumkov commented on packages/dpns-contract/schema/v1/dpns-contract-documents.json
> +    "documentsMutable": false,
We should do it with data trigger so we can make them updatable easily in future.

2024-06-24 11:40 UTC, QuantumExplorer requested changes

2024-06-24 11:40 UTC, QuantumExplorer commented on packages/dpns-contract/schema/v1/dpns-contract-documents.json
> +    "documentsMutable": false,
Use a data trigger here, and have mutable: true, canBeDeleted: true
Also add transferable: 1, tradeMode: 1

Then use data triggers for now to restrict everything.

2024-06-24 11:40 UTC, QuantumExplorer commented on packages/dpns-contract/schema/v1/dpns-contract-documents.json
> +    "documentsMutable": false,
Needs "canBeDeleted": true to make it explicit.

2024-06-24 11:40 UTC, QuantumExplorer commented on packages/masternode-reward-shares-contract/schema/v1/masternode-reward-shares-documents.json
> -        ]
Bring it back

2024-06-27 08:19 UTC, shumkov commented on packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/documents_batch/data_triggers/triggers/dashpay/v0/mod.rs
> +    // TODO: Calculate fee operations
@QuantumExplorer this question for you

2024-07-01 13:37 UTC, QuantumExplorer submitted a review, later dismissed

2024-07-05 14:11 UTC, merged