logging for devnet upgrade protocol test
dashpay/platform pull request #1925
Opened 2024-07-04 08:02 UTC by ogabrielides

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2024-07-04 10:00 UTC, shumkov requested changes

2024-07-04 10:00 UTC, shumkov commented on packages/rs-drive-abci/src/execution/platform_events/protocol_upgrade/check_for_desired_protocol_upgrade/v0/mod.rs
> +                tracing::info!(
I would move it there https://github.com/dashpay/platform/blob/a12abe641322e503b1cce4195b34783750a77938/packages/rs-drive-abci/src/execution/platform_events/protocol_upgrade/upgrade_protocol_version/v0/mod.rs#L68-L67

2024-07-05 15:25 UTC, shumkov requested changes

2024-07-05 15:25 UTC, shumkov commented on packages/rs-drive-abci/src/execution/platform_events/protocol_upgrade/upgrade_protocol_version/v0/mod.rs
> +                    "Next epoch protocol version: current epoch_index: {}, next_protocol_version: {}",
next protocol version set to {protocol_version}

2024-07-05 15:25 UTC, shumkov commented on packages/rs-drive-abci/src/execution/platform_events/protocol_upgrade/check_for_desired_protocol_upgrade/v0/mod.rs
> +            "Check protocol upgrade: check_for_desired_protocol_upgrade: total_hpmns: {}, required_upgraded_hpmns: {}, current_votes: {}, versions_passing_threshold: {}",
"Protocol version voting is finished. {} versions passing the threshold: {:?}", versions_passing_threshold.len(), versions_passing_threshold

2024-07-05 15:46 UTC, ogabrielides commented on packages/rs-drive-abci/src/abci/handler/prepare_proposal.rs
> +        "Prepared proposal with {} transition{} for height: {}, round: {}, storage_fees: {}, processing_fees: {} in {} ms",
I didn't understand this suggestion. Can you explain please @shumkov ?

2024-07-08 08:08 UTC, shumkov commented on packages/rs-drive-abci/src/abci/handler/prepare_proposal.rs
> +        "Prepared proposal with {} transition{} for height: {}, round: {}, storage_fees: {}, processing_fees: {} in {} ms",
Tracing event accept params and message. I suggested to do out include fees into message and keep only in params to do mot overcomplicate it

2024-07-08 11:09 UTC, shumkov commented on packages/rs-drive-abci/src/execution/platform_events/protocol_upgrade/check_for_desired_protocol_upgrade/v0/mod.rs
> +            current_votes = votes_str,
all_votes = ?protocol_versions_counter.global_cache

2024-07-08 11:21 UTC, shumkov commented on packages/rs-drive-abci/src/execution/platform_events/protocol_upgrade/check_for_desired_protocol_upgrade/v0/mod.rs
> +        drop(protocol_versions_counter);
Same here

2024-07-08 11:21 UTC, shumkov requested changes

2024-07-08 11:21 UTC, shumkov commented on packages/rs-drive-abci/src/execution/platform_events/protocol_upgrade/check_for_desired_protocol_upgrade/v0/mod.rs
> +            drop(protocol_versions_counter);
This variable will be dropped on the next line. I don't think you need to do explicitly.

2024-07-08 12:55 UTC, shumkov approved these changes
👍

2024-07-08 13:08 UTC, merged