feat: reproducible builds
dashpay/platform pull request #1983
Opened 2024-07-22 01:49 UTC by QuantumExplorer

## Issue being fixed or feature implemented
This makes some changes so that we can make reproducible builds.

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added or updated relevant unit/integration/functional/e2e tests
- [X] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [x] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2024-07-23 00:44 UTC, PastaPastaPasta commented on .cargo/config.toml
> +debug = false
it's not clear which args are needed specifically to result in reproducibility; what concerns do you have about specifying these options even if they as default?

2024-07-23 00:44 UTC, PastaPastaPasta commented on .cargo/config.toml
> +rustflags = ["-C", "target-feature=-crt-static"]
I don't believe this is the case: see slack for more discussion

2024-07-31 13:06 UTC, shumkov requested changes

2024-07-31 13:06 UTC, shumkov commented on .cargo/config.toml
> +    "-C", "strip=debuginfo"
Just do 
strip = "debuginfo"

2025-09-03 16:18 UTC, QuantumExplorer commented
Stale

2025-09-03 16:18 UTC, closed without merging