build: update dependences
dashpay/platform pull request #2072
Opened 2024-08-23 11:28 UTC by lklimek

## Issue being fixed or feature implemented

Updated dependencies

## What was done?

* updated multiple dependencies
* removed atty dependency which is not needed anymore, as the feature is already in rust std lib
* updated source code to reflect dependency changes, mainly in `derive_more` 

TODO:

* update rs-tenderdash-abci to 1.2 once it's releeased

Note: requires #2070 to be merged first

## How Has This Been Tested?

GHA

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2024-09-04 13:49 UTC, shumkov commented
It seems the branch is outdated since I see changes from other PRs

2024-10-07 08:26 UTC, lklimek commented on packages/rs-dpp/src/state_transition/state_transitions/document/documents_batch_transition/document_transition/document_purchase_transition/v0/mod.rs
> +#[display( "Base: {}", "base")]
Only derive_more 1.0 is in use

2024-10-07 09:14 UTC, shumkov requested changes

2024-10-07 09:14 UTC, shumkov commented on Dockerfile
> +ARG PROTOC_VERSION=27.3
Please update readme and dev container

2024-10-07 09:18 UTC, shumkov approved these changes

2024-10-07 09:35 UTC, QuantumExplorer approved these changes

2024-10-07 09:36 UTC, lklimek commented on Dockerfile
> +ARG PROTOC_VERSION=27.3
done

2024-10-07 09:40 UTC, QuantumExplorer approved these changes

2024-10-07 09:41 UTC, shumkov approved these changes

2024-10-07 11:34 UTC, merged