refactor(platform): replace bls library
dashpay/platform pull request #2257
Opened 2024-10-19 10:16 UTC by QuantumExplorer

## Issue being fixed or feature implemented
bls-signatures built from c++ had a lot of compilation issues for Windows. In this PR we replace it with https://crates.io/crates/blsful/3.0.0-pre6

## What was done?
Of note: the serialization for Platform version does change and needs to be checked, it should work though

## How Has This Been Tested?
Tests still pass

## Breaking Changes
Should not require a platform version change.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [x] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2024-11-15 14:33 UTC, lklimek commented
Local devnet on BLS branch fails with:
```
errors=[Abci(InvalidChainLock("received a chain lock for height 1 that we figured out was invalid based on platform state ChainLock
```

2024-11-20 09:24 UTC, QuantumExplorer commented on packages/rs-dpp/src/identity/identity_public_key/methods/hash/mod.rs
> +        private_key_bytes: &[u8; 32],
Done.

2024-11-20 09:25 UTC, QuantumExplorer commented on packages/rs-dpp/src/core_types/validator_set/mod.rs
> +use crate::bls_signatures::{Bls12381G2Impl, PublicKey as BlsPublicKey};
No need.

2024-11-20 09:26 UTC, QuantumExplorer commented on packages/rs-dpp/src/identity/random.rs
> +            + Extend<(IdentityPublicKey, [u8; 32])>,
Must have been previously fixed.

2024-11-20 09:54 UTC, QuantumExplorer commented on packages/rs-dpp/src/bls/native_bls.rs
> +            Err(_) => Err(anyhow!("Verification failed").into()),
fixed

2024-11-20 09:54 UTC, QuantumExplorer commented on packages/rs-dpp/src/bls/native_bls.rs
> +        let public_key_bytes = public_key.0.to_compressed().to_vec();
This is not my library.

2024-11-20 09:54 UTC, QuantumExplorer commented on packages/rs-dpp/src/bls/native_bls.rs
> +            .ok_or(anyhow!("Incorrect Priv Key"))?;
Fixed

2024-11-20 09:55 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/platform_types/signature_verification_quorum_set/v0/for_saving_v1.rs
> +    previous_quorums: Option<PreviousPastQuorumsForSavingV0>,
intentional.

2024-11-20 09:59 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/platform_types/platform_state/v0/old_structures/mod.rs
> +                .unwrap(),
I used an expect instead.

2024-11-20 09:59 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/platform_types/signature_verification_quorum_set/mod.rs
> +use crate::platform_types::signature_verification_quorum_set::v0::for_saving_v1::SignatureVerificationQuorumSetForSavingV1;
this is okay.

2024-11-20 10:00 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/platform_types/signature_verification_quorum_set/mod.rs
> +    V1(SignatureVerificationQuorumSetForSavingV1),
Fixed

2024-11-20 10:01 UTC, QuantumExplorer commented on packages/rs-dpp/src/signing.rs
>                  };
this is okay.

2024-11-20 11:31 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/platform_types/commit/v0/mod.rs
> +                signature
already had been fixed

2024-11-20 11:32 UTC, QuantumExplorer commented on packages/rs-dpp/src/signing.rs
>                  };
nevermind, i took this suggestion.

2024-11-20 11:35 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/platform_types/signature_verification_quorum_set/v0/for_saving.rs
> +                .expect("expected to convert between BLS key libraries (to chia)"),
This is something that happens once and can not really fail, expect is fine.

2024-11-20 16:05 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/platform_types/signature_verification_quorum_set/v0/for_saving.rs
> +                    .expect("expected to convert between BLS key libraries (from chia)"),
This is fine, as we already had verified it was correct.

2024-11-20 16:09 UTC, QuantumExplorer commented on packages/rs-drive-abci/tests/strategy_tests/masternode_list_item_helpers.rs
> +                        private_key_operator.public_key().0.to_compressed().to_vec();
fixed

2024-11-20 16:13 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/mimic/test_quorum.rs
> +};
it's fine

2024-11-20 16:14 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/mimic/test_quorum.rs
> +                        .expect("expected conversion to work"),
fixed

2024-11-20 16:15 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/mimic/test_quorum.rs
> +                        .expect("expected conversion to work"),
no, this is fine

2024-11-20 20:33 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/mimic/test_quorum.rs
> +                    pub_key_share: Some(public_key.0.to_compressed().to_vec()),
Already done.

2024-11-20 20:36 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/mimic/test_quorum.rs
> +                .expect("expected conversion to work"),
this is fine.

2024-11-20 20:37 UTC, QuantumExplorer commented on packages/rs-dpp/src/identity/identity_public_key/v0/methods/mod.rs
> +        let invalid_private_key_bytes = [0u8; 32];
already done.

2024-11-20 20:37 UTC, QuantumExplorer commented on packages/rs-drive-abci/src/platform_types/validator_set/v0/mod.rs
> +                                            )),
This is fine.

2024-11-20 20:38 UTC, QuantumExplorer commented on packages/rs-dpp/src/core_types/validator_set/v0/mod.rs
> +        let public_key_bytes = self.threshold_public_key.0.to_compressed();
already done.

2024-11-20 20:39 UTC, QuantumExplorer commented on packages/rs-dpp/src/core_types/validator_set/v0/mod.rs
> +            hex::encode(self.threshold_public_key.0.to_compressed()) // Assuming BlsPublicKey is a byte array
already done.

2024-11-20 20:40 UTC, QuantumExplorer commented on packages/rs-dpp/src/core_types/validator_set/v0/mod.rs
> +            })?;
Done.

2024-11-20 20:40 UTC, QuantumExplorer commented on packages/rs-dpp/src/core_types/validator_set/v0/mod.rs
> +            })?;
Done.

2024-11-20 20:41 UTC, QuantumExplorer commented on packages/rs-dpp/src/identity/identity_public_key/key_type.rs
> +                let secret_key = dashcore::secp256k1::SecretKey::from_byte_array(private_key_bytes)
already done.

2024-11-20 20:41 UTC, QuantumExplorer commented on packages/rs-drive-abci/tests/strategy_tests/query.rs
> +    pub public_key: &'a dpp::bls_signatures::PublicKey<Bls12381G2Impl>,
already done.

2024-11-20 20:41 UTC, QuantumExplorer commented on packages/rs-dpp/src/identity/identity_public_key/key_type.rs
> +                let secret_key = dashcore::secp256k1::SecretKey::from_byte_array(private_key_bytes)
already done.

2024-11-20 20:43 UTC, QuantumExplorer commented on packages/rs-drive-abci/tests/strategy_tests/masternodes.rs
> +        let pub_key_operator = private_key_operator.public_key().0.to_compressed().to_vec();
this is done on purpose

2024-12-12 11:00 UTC, shumkov requested changes

2024-12-12 11:01 UTC, shumkov requested changes
Change base to v1.8-dev

2024-12-16 09:28 UTC, QuantumExplorer commented on packages/rs-dpp/src/bls/native_bls.rs
> +use std::array::TryFromSliceError;
Fixed.

2024-12-16 09:29 UTC, QuantumExplorer commented on packages/rs-dpp/src/errors/protocol_error.rs
> +use std::array::TryFromSliceError;
Fixed

2024-12-16 10:47 UTC, merged