Refactor/sdk put dry
dashpay/platform pull request #2338
Opened 2024-11-20 12:58 UTC by lklimek

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2024-11-28 12:19 UTC, lklimek commented
@coderabbitai review all

2024-12-05 00:33 UTC, shumkov requested changes

2024-12-05 00:33 UTC, shumkov commented on packages/rs-sdk/src/platform/transition/purchase_document.rs
>  pub trait PurchaseDocument<S: Signer> {
Why you didn't add super trait Waitable here?

2024-12-05 00:33 UTC, shumkov commented on packages/rs-sdk/src/platform/transition/put_contract.rs
> +pub trait PutContract<S: Signer>: Waitable {
In other cases you don't add super trait so you need to use `<Self as Waitable>::`. I think this approach is cleaner

2024-12-05 00:33 UTC, shumkov commented on packages/rs-sdk/src/sdk.rs
> +        let dapi_client_settings = self.settings.unwrap_or(DEFAULT_REQUEST_SETTINGS);
I think you need to merge passed setting on top of default setting, not replace. We can deal with settings in a separate PR. Let's discuss it and create a task.

2024-12-05 00:33 UTC, shumkov commented on packages/rs-sdk/src/platform/transition/waitable.rs
> +pub trait Waitable: Sized {
I'm not sure this structure is the best, when we have all our entities used in one module. I think we should split code by domain entities: document related modules where we have everything about documents and so on. Let's discuss and create a task

2024-12-05 09:40 UTC, shumkov approved these changes

2024-12-05 11:59 UTC, shumkov approved these changes

2024-12-05 12:09 UTC, merged