chore: change grpc-web library
dashpay/platform pull request #628
Opened 2022-11-21 15:18 UTC by markin-io

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-11-21 15:47 UTC, shumkov commented
We probably don't want to introduce such radical change to v0.23 which more or less stable and almost ready to release

2022-11-22 02:24 UTC, strophy commented
Hi @markin-io can you please fill in the description of this PR so I can understand the purpose of this change?

2022-11-24 18:43 UTC, markin-io commented on packages/dapi-grpc/browser.js
> +      parsedMetadata[key] = values.join(', ');
Make sure it's compliant with grpc-js Metadata

2022-11-25 08:56 UTC, markin-io commented on packages/js-dapi-client/lib/transport/GrpcTransport/createGrpcTransportError.js
> +    } else if (grpcError.metadata.headersMap) {
Fixed

2022-11-25 15:54 UTC, shumkov requested changes

2022-11-25 15:54 UTC, shumkov commented on packages/js-dash-sdk/src/SDK/Client/Platform/broadcastStateTransition.ts
> +        grpcError.metadata = error.data;
Could you please add a comment / todo to explain this

2022-12-04 04:51 UTC, shumkov approved these changes
Looks good as a first iteration 👍

2022-12-07 10:43 UTC, shumkov approved these changes
LGTM 👍

2022-12-07 10:44 UTC, merged