feat: support estimated costs and grove6
dashpay/platform pull request #642
Opened 2022-11-28 08:31 UTC by QuantumExplorer

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-12-08 12:27 UTC, shumkov requested changes

2022-12-08 12:27 UTC, shumkov commented on packages/rs-drive/Cargo.toml
> +branch = "master"
Shall we use git tag?

2022-12-08 12:27 UTC, shumkov commented on packages/rs-drive/src/drive/document/estimation_costs.rs
> +    //
Commented code

2022-12-08 12:55 UTC, QuantumExplorer commented on packages/rs-drive/Cargo.toml
> +branch = "master"
Okay

2022-12-08 16:23 UTC, shumkov approved these changes
Don't really understand what is really written here but from the first perspective, it looks fine.

2022-12-09 06:57 UTC, shumkov approved these changes

2022-12-09 07:01 UTC, merged