feat(dashmate): improve dashd templating
dashpay/platform pull request #692
Opened 2022-12-22 09:53 UTC by pshenmic

## Issue being fixed or feature implemented

Merge some templating features for dashd from https://github.com/dashpay/dash-network-deploy. This is needed for dashmate integration for dash-network-deploy.

## What was done?

Added template params for:
* logips
* listen
* allowprivatenet
* indexes
* zmqport
* minimumdifficultyblocks
* powtargetspacing

## How Has This Been Tested?

Locally

## Breaking Changes

Added more fields for core in dashmate config.json

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-12-22 12:06 UTC, shumkov requested changes

2022-12-22 21:39 UTC, pshenmic commented on packages/dashmate/templates/core/dash.conf.dot
> +llmqinstantsenddip0024=llmq_devnet_dip0024
Isnt it devnet only?

2022-12-23 02:18 UTC, shumkov requested changes

2022-12-23 02:18 UTC, shumkov commented on packages/dashmate/configs/migrations.js
> +        config.core.minimumDifficultyBlocks = 1000;
I guess this setting should depend on the network, isn't it?

2022-12-23 02:18 UTC, shumkov commented on packages/dashmate/configs/system/base.js
> +    listen: 1,
I believe you meant `logIps`

2022-12-23 02:18 UTC, shumkov commented on packages/dashmate/templates/core/dash.conf.dot
> +{{? it.core.logIps === true}}
You values only 0 and 1

2022-12-23 08:50 UTC, shumkov requested changes

2022-12-23 08:50 UTC, shumkov commented on packages/dashmate/configs/schema/configJsonSchema.js
> +          minimum: 1,
0

2022-12-23 09:12 UTC, shumkov commented on packages/dashmate/configs/migrations.js
> +        config.core.minimumDifficultyBlocks = 1000;
I would honestly keep it 0 by default

2022-12-23 09:12 UTC, shumkov commented on packages/dashmate/configs/system/base.js
> +    minimumDifficultyBlocks: 1000,
I would keep it 0 by default

2022-12-23 09:13 UTC, shumkov commented on packages/dashmate/configs/system/base.js
> +    powTargetSpacing: 150,
is it 2.5 min?

2022-12-23 09:15 UTC, pshenmic commented on packages/dashmate/configs/system/base.js
> +    powTargetSpacing: 150,
Yes, in seconds

2022-12-23 09:45 UTC, shumkov submitted a review, later dismissed
👍

2022-12-28 08:15 UTC, shumkov requested changes

2022-12-28 08:15 UTC, shumkov commented on packages/dashmate/configs/schema/configJsonSchema.js
> +                type: 'string',
format: ipv4

2022-12-28 08:19 UTC, shumkov approved these changes
👍

2022-12-28 10:49 UTC, shumkov approved these changes

2022-12-28 11:17 UTC, merged