chore: initial commit
dashpay/platform pull request #736
Opened 2023-01-17 11:19 UTC by jawid-h

## Issue being fixed or feature implemented

Trying to solve WSL2 restart issue using dynamic ENV variable for Core container

## What was done?

- updated docker-compose file and generating ENV variable using `Date()`

## How Has This Been Tested?

local env

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2023-01-17 11:33 UTC, shumkov requested changes

2023-01-17 11:33 UTC, shumkov commented on packages/dashmate/src/docker/DockerCompose.js
> +      CORE_WSL2_FIX: (new Date()).getTime(),
We should do that only for WSL, not for other envs

2023-01-17 11:33 UTC, shumkov commented on packages/dashmate/docker-compose.yml
> +      - WSL2_FIX=${CORE_WSL2_FIX}
Please add comprehensive comment to describe the problem and the solution

2023-01-17 14:21 UTC, shumkov requested changes

2023-01-17 14:21 UTC, shumkov commented on packages/dashmate/src/docker/DockerCompose.js
> +      CORE_WSL2_FIX: (new Date()).getTime(),
I guess this line needs to be removed

2023-01-17 16:53 UTC, jaboski commented
Dashmate-helper crashing for me with:
`Cannot read properties of undefined (reading 'log')`
Sent you full log of the error. 
Steps:
- yarn dashmate setup local
- yarn dashmate group start

2023-01-17 18:59 UTC, pshenmic commented
@jaboski sorry it was messed up by my last commits. this pr should resolve it 
https://github.com/dashpay/platform/pull/738

@jawid-h could you kindly pull this in?

2023-01-18 05:17 UTC, jawid-h commented
@jaboski @pshenmic Merged #738

2023-01-18 07:58 UTC, pshenmic commented on packages/dashmate/src/docker/DockerCompose.js
> +      env.CORE_WSL2_FIX = (new Date()).getTime();
I think `WSL2_FIX` is meant to be here as it will be applied to all containers

2023-01-18 11:18 UTC, shumkov submitted a review, later dismissed
👍

2023-01-18 11:56 UTC, shumkov approved these changes
👍

2023-01-18 12:15 UTC, jaboski commented
No more issue with crashing dashmate-helper. I also checked setup, start, stop, restart and reset for local - works fine for me 👍

2023-01-18 13:08 UTC, merged