feat(rs-dpp): validate indices are backwards compatible backport
dashpay/platform pull request #797
Opened 2023-02-21 20:01 UTC by markin-io

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2023-02-22 04:49 UTC, jawid-h commented
Please fix Clippy warnings and check why CI is failing, apart from that looks OK to me

2023-02-22 08:40 UTC, qrayven approved these changes

2023-02-23 01:51 UTC, shumkov requested changes
Please fix clippy warning

2023-02-23 01:53 UTC, shumkov commented on packages/rs-dpp/src/data_contract/state_transition/data_contract_update_transition/validation/basic/validate_indices_are_backward_compatible.rs
> +                    let indices_array = indices.as_array().expect("Indices must be an array");
Do we use expect in production code?

2023-02-23 12:33 UTC, markin-io commented on packages/rs-dpp/src/data_contract/state_transition/data_contract_update_transition/validation/basic/validate_indices_are_backward_compatible.rs
> +                    let indices_array = indices.as_array().expect("Indices must be an array");
fixed

2023-02-23 14:05 UTC, shumkov requested changes

2023-02-23 14:05 UTC, shumkov commented on packages/rs-dpp/src/data_contract/state_transition/data_contract_update_transition/validation/basic/validate_indices_are_backward_compatible.rs
> +                    let indices_array = indices.as_array().unwrap();
We don't do unwap neither. It will be panic as well. You should return an error

2023-02-23 20:52 UTC, shumkov approved these changes

2023-02-24 10:26 UTC, merged