feat(dashmate): implement http json rpc api
dashpay/platform pull request #888
Opened 2023-04-06 09:45 UTC by pshenmic

## Issue being fixed or feature implemented

JSON RPC api wrapper around dashmate enables programmatic invocation of dashmate commands. It allows you remotely execute commands and fetch node status. Developers will be able to build an UI on top of it.

## What was done?

* Added JSON RPC api

## How Has This Been Tested?

Locally

## Breaking Changes

No

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-04-06 09:48 UTC, pshenmic commented
888 😈😈

2023-04-06 10:57 UTC, shumkov requested changes

2023-04-06 10:57 UTC, shumkov commented on packages/dashmate/configs/schema/configJsonSchema.js
> +            jsonRpc: {
Let's rename to API

2023-04-06 10:57 UTC, shumkov commented on packages/dashmate/configs/schema/configJsonSchema.js
>            required: ['docker'],
It must be here as well

2023-04-06 10:57 UTC, shumkov commented on packages/dashmate/configs/system/local.js
> +      jsonRpc: {
api

2023-04-06 10:57 UTC, shumkov commented on packages/dashmate/scripts/helper.js
> +const httpApiFactory = require('../src/helper/api/httpApiFactory')(async function main() {
It looks super unreadable. You should use container to resolve HTTP server

2023-04-06 10:57 UTC, shumkov commented on packages/dashmate/scripts/helper.js
> +  httpApi(container);
You can specify `container` inside as a dependency if you need

2023-04-06 10:57 UTC, shumkov commented on packages/dashmate/src/helper/api/httpApiFactory.js
> +function httpApiFactory() {
you should put container dependencies here

2023-04-06 10:57 UTC, shumkov commented on packages/dashmate/src/listr/tasks/setup/setupLocalPresetTaskFactory.js
> +                  config.set('dashmate.helper.jsonRpc.port', config.get('dashmate.helper.jsonRpc.port') + (i * 100));
You open port for each config?

2023-04-06 11:33 UTC, pshenmic commented on packages/dashmate/src/listr/tasks/setup/setupLocalPresetTaskFactory.js
> +                  config.set('dashmate.helper.jsonRpc.port', config.get('dashmate.helper.jsonRpc.port') + (i * 100));
Yes

2023-04-06 14:04 UTC, shumkov approved these changes
👍

2023-04-07 02:55 UTC, shumkov approved these changes

2023-04-07 06:46 UTC, merged