feat: wasm-dpp-integration
dashpay/platform pull request #984
Opened 2023-04-26 17:35 UTC by markin-io

## Issue being fixed or feature implemented

Backport of https://github.com/dashpay/platform/pull/848

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-04-27 22:51 UTC, strophy commented
What backend is sccache using here, does it depend on the GitHub Actions cache? Did you test this works on AWS self-hosted runners?

2023-04-28 04:40 UTC, shumkov requested changes

2023-04-28 04:40 UTC, shumkov commented on .github/workflows/all-packages.yml
>            toolchain: stable
Are you sure that you aren't doing duplicate stuff here?

2023-04-28 04:41 UTC, shumkov commented on .github/workflows/all-packages.yml
>            toolchain: stable
There are more CI related commits in v0.24 so I would back port all together otherwise it will be a mess

2023-04-28 09:41 UTC, markin-io commented
@strophy the change was cherry picked as is from v0.24.
No other CI related manipulations were made

2023-04-28 09:43 UTC, shumkov commented on .github/workflows/all-packages.yml
>            toolchain: stable
Agreed to keep it as it is since CI doesn't work in 25 anyways and then make a separate PR to put the workflows in v0.25 in order

2023-04-28 09:44 UTC, shumkov approved these changes
👍

2023-04-28 09:44 UTC, merged